#!/bin/bash

OPTIND=1
generateZip=false
gitTree=false
showHelp=false

while getopts "z:t:h:" opt; do
	case $opt in
		t) gitTree=$OPTARG
			;;
		z) generateZip=true
			;;
		h) showHelp=true
			;;
	esac
done

if $showHelp; then
	echo "usage: do/help/build [options]"
	echo "-h: Show this help text and exit"
	echo "-t: The git tree or index to checkout"
	echo "-z: Set to \"true\" to generate a zip archive of the help files"
	exit 0
fi

tempDir="`mktemp -d`"
cp -r grails-app/conf/help/* $tempDir
cp -r web-app/* $tempDir
for f in $(find $tempDir -name \*.txt); do
	filename=$(basename "$f")
	filenameWithoutExtension="${filename%.*}"
	pandoc --from=markdown --to=html $f -o $(dirname ${f})/$filenameWithoutExtension
	rm $f
done

for f in $(ls web-app | grep images --invert-match); do
	rm -rf "$tempDir/$f"
done

for f in $(ls web-app/images | grep help --invert-match); do
	rm -rf "$tempDir/images/$f"
done

mkdir -p target/generated_help; cp -r $tempDir/* $_
if $generateZip; then
	echo "Generating ZIP archive"
	zip target/help.zip -r $tempDir
	echo "ZIP saved at target/help.zip"
fi

google-chrome target/generated_help

exit 0

