#!/bin/bash
set -e

echo "#############################################"
echo "## This script aims to test new installers ##"
echo "## 1. Build installer                      ##"
echo "## 2. uninstall old installation           ##"
echo "## 3. install new version                  ##"
echo "## 4. run new version                      ##"
echo "## 5. check that the server is working!    ##"
echo "#############################################"

PROJECT_DIR=../frontlinesms-core

echo "# clean target directories"
rm -rf $PROJECT_DIR/target/
rm -rf $PROJECT_DIR/install/target*
rm -rf $PROJECT_DIR/install/src/web-app/

echo "# build-installers"
grails clean
grails -Dfrontlinesms2.build.confirmNotProd=true build-installers $@

do/uninstall_install_test

