#!/bin/bash
set -e
if [ -z $1 ]; then
	GRAILS_ENV=prod
else
	GRAILS_ENV=$1
fi
echo "# running grails clean..."
grails clean
echo "# build installers with migrations disabled for grails env $GRAILS_ENV..."
grails -Dfrontlinesms2.build.db.migrations=false $GRAILS_ENV build-installers
echo "# installers built.  Have a nice day."

