#!/bin/bash
set -e
echo "# running grails clean..."
grails clean
echo "# clean complete."
echo "# building installers in prod environment..."
grails prod build-installers
echo "# installers built."
echo "# making linux installer executable..."
chmod +x install/target/install4j/*.sh
echo "# all done."

