#!/bin/bash
echo "# Checking for bad calls to template renderer..."
echo "# Checking views..."
grep -rn "render.*template" grails-app/views/ | grep -v "fsms:render"
VIEW_OUTPUT=$?

if [ "$VIEW_OUTPUT" -eq 1 ]; then
	echo "# No bad template renders detected"
	exit 0
else
	echo "# Bad template renders detected"
	exit 1
fi

