#!/bin/bash
echo "# Searching for flash.message assignments"
grep -Er 'flash\.message\s=' grails-app/
result="$?"

if [[ "$result" == "1" ]]; then
	echo "# No use of flash.message detected"
	exit 0
fi

if [[ "$result" == "0" ]]; then
	echo "# Bad calls to flash.message found"
	exit 1
fi

echo "# There was a problem searching for calls to System.env and System.properties."
exit $?

