#!/bin/bash
echo "# Checking for calls to metaclass on non-instance variables..."
grep -r '\s[A-Z]([a-zA-Z]*)\.metaClass' test/integration/ test/functional/
if [ $? -eq 1 ]; then
	echo "# No bad metaclass calls found."
	exit 0
fi
echo "# Bad Class.metaClass calls detected."
exit 1

