#!/bin/bash

echo "Starting grails in database development mode..."
echo "Calling 'grails -Dgrails.env=dbDev -Ddisable.auto.recompile=false -Dfrontlinesms2.bootstrap.data=true $@'"
grails -Dgrails.env=dbDev -Ddisable.auto.recompile=false -Dfrontlinesms2.bootstrap.data=true $@

