#!/bin/bash
# S3 Deployment script for FrontlineSMS. Requires $FRONTLINESMS_SSH_USER
# and # $FRONTLINESMS_SSH_PASS to be set and valid.
set -e

#check if $FRONTLINESMS_SSH_USER and $FRONTLINESMS_SSH_PASS env variables are set
if [ -z "$FRONTLINESMS_SSH_USER" ] && [ -z "$FRONTLINESMS_SSH_PASS" ] ; then
	echo "[error] FRONTLINESMS_SSH_USER or FRONTLINESMS_SSH_PASS has not been set"
	exit 1
fi
# get local filename/path
fileName() {
	echo "$(ls install/target/install4j/ | grep $1)"
}
localPath() {
	echo "$(ls install/target/install4j/frontlinesms* | grep $1)"
}

# upload files to S3 bucket & verify afterwards
s3Upload() {
	echo "Uploading to S3 bucket"
	s3cmd put --acl-public --guess-mime-type $1 s3://${bucketName}/$2
	s3cmd get s3://${bucketName}/$2 ${tempDir}/$1

	md5Loc=$(md5sum $1 | awk '{print $1}')
	md5Rem=$(md5sum ${tempDir}/$1 | awk '{print $1}')
	echo "Local md5 checksum:  $md5Loc"
	echo "Remote md5 checksum: $md5Rem"

	if [ "$md5Loc" != "$md5Rem" ] ; then
		echo "... verification failed, exiting script"
		exit 1
	else
		echo "... verification successful"
	fi
}

# 0. vars & set up
bucketName="download-frontlinesms"
serverUrl="ftp://frontlinesms.com/"
serverPath="subdomains/wip/httpdocs/dl/"

tempDir=".tmp-$RANDOM"
echo "Creating temporary directory at $tempDir"
mkdir $tempDir
echo "Setting up S3 access tokens"
do/setUpS3

touch ${tempDir}/.htaccess

for osArch in "windows" "mac" "unix"; do
	echo "Processing $osArch build..."
	# 1. get paths & file names
	osArchFilePath=$(localPath $osArch)
	osArchFile=$(fileName $osArch)
	
	echo "Uploading $osArchFile"
	# 2. upload and verify
	s3Upload $osArchFilePath $osArchFile

	# 3. rewrite .htaccess
	s3Link="http://$bucketName.s3.amazonaws.com/${osArchFile}"
	echo "Creating redirect statement in .htaccess to $s3Link"

	echo "Redirect /dl/latest/$osArch $s3Link" >> ${tempDir}/.htaccess
done

echo "Rewrote .htaccess with the following contents:"
cat ${tempDir}/.htaccess

# 4. publish .htaccess
echo "Pushing .htaccess file to $serverUrl$serverPath"
curl -T "${tempDir}/.htaccess" -u $FRONTLINESMS_SSH_USER:\
$FRONTLINESMS_SSH_PASS -Q "TYPE I" "$serverUrl$serverPath"

echo "Cleaning up $tempDir"
# 5. cleanup
rm -R $tempDir

echo "Complete"
