#!/bin/bash
if [ "$1" == "-v" ]; then
	echo "Should set first"
	VERBOSE=true
	shift
fi
VIOLATIONS=0

echo "# All domain saves should be flushed in functional tests"
BAD_SAVE_COUNT=`grep -r "save(.*)" test/functional/ | grep -v "flush:\s*true" | grep -c .`
if [ "0" -ne "$BAD_SAVE_COUNT" ]; then
	echo "# Found saves without flush: $BAD_SAVE_COUNT"
	let ++VIOLATIONS
	if [ -n "$VERBOSE" ]; then
		grep -r "save(.*)" test/functional/ | grep -v "flush:\s*true"
	fi
else
	echo "# No bad saves found"
fi

if [ $VIOLATIONS -gt "0" ]; then
	echo "# Violations: $VIOLATIONS"
	exit 1
fi

echo "# There were no violations"
