#!/bin/bash

echo "# All domain saves should be flushed in functional tests"
grep -r "save(.*)" test/functional/ | grep -Ev "flush:\s*true|no-flush-deliberate"
searchResult=$?
if [[ "$searchResult" == "0" ]]; then
	echo "# Found saves without flush."
	exit 1
elif [[ "$searchResult" == "1" ]]; then
	echo "# No bad saves found."
	exit 0
fi

echo "# Error with search.  Terminating script."
exit 1

