#!/bin/bash
echo "Generating report on completeness of translations in grails-app/i18n/ ..."
for f in grails-app/i18n/messages_*.properties; do echo "Processing $f file.."; groovy do/i18n-compare.groovy grails-app/i18n/messages.properties $f; echo "----"; done >> i18nreport.txt
echo "Report generated in i18nreport.txt"
