#!/bin/bash
function check_npm_module_available() {
	MODULE_NAME=$1
	echo "# Checking for NPM module: $MODULE_NAME..."
	INSTALL_COUNT=`(npm list; npm -g list) | grep -c "^[├└]─[─┬] $MODULE_NAME\@"`
	if [ 0 -eq $INSTALL_COUNT ]; then
		echo "# NPM module missing: $MODULE_NAME.  Please run 'npm install $MODULE_NAME' or 'sudo npm i -g $MODULE_NAME'"
		exit 1
	fi
	echo "# NPM Module found: $MODULE_NAME"
}
check_npm_module_available fs
check_npm_module_available jquery
check_npm_module_available jsdom
check_npm_module_available qunit

set -e

function run_test() {
	TARGET=$1
	echo "# Running tests for $TARGET..."
	qunit -c "web-app/js/${TARGET}.js" -d `ls test/js/lib/*.js` -t "test/js/${TARGET}_tests.js"
}

pushd test/js
TESTS=`ls *_tests.js | sed -e "s/_tests.js//"`
popd
echo "# Tests to run: $TESTS"

run_test recipient_selecter

