#!/bin/bash
# TODO run each file separately and process into target/plugins/frontlinesms-core/$ORIGINAL_PATH
# TODO load predefs from web-app/js global vars
TEMP_JS=target/temp.js
find grails-app/views/ -name "*.gsp" -print | xargs sgrep '("<r:script".."</r:script>") or ("<g:javascript".."</g:javascript>") or ("<script".."</script>")' | grep -E -v "r:script|g:javascript|<script|</script>" > $TEMP_JS
do/jslint $TEMP_JS
