#!/bin/bash
# TODO run each file separately and process into target/plugins/frontlinesms-core/$ORIGINAL_PATH
# TODO load predefs from web-app/js global vars

TEMP_JS=target/temp.js
do/extract_js_from_gsps

echo "# Linting..."
do/jslint $TEMP_JS
echo "# Lint complete."
