#!/bin/bash
set -e

# Extract flags to pass to jslint
EXTRA_FLAGS=""
while [[ $1 == "--"* ]]; do
	if [ -z "$EXTRA_FLAGS" ]; then
		EXTRA_FLAGS=$1
	else
		EXTRA_FLAGS="$EXTRA_FLAGS $1"
	fi
	shift
done

echo "# Flags to pass directly to jslint: $EXTRA_FLAGS"
echo "# Other args: $@"

# check spidermonkey is installed
jslint || echo "# Please install jslint"

# check that jslint is available in temp

# run jslint
if [ -z "$@" ]; then
	do/extract_js_from_gsps
	FILES=`find web-app/js/ -name "*.js" | grep -v jqplot | grep -v jquery`
	FILES="$FILES target/temp.js"
else
	FILES="$@"
fi

echo "# Linting: $FILES"
jslint --white --sloppy --white --browser --nomen --plusplus --forin --undef $EXTRA_FLAGS \
--predef $ \
--predef jQuery \
--predef url_root \
--predef i18n \
--predef initializePopup \
-- $FILES
