#!/bin/sh
set -e

# check spidermonkey is installed
jslint || echo "Please install jslint"

# check that jslint is available in temp

# run jslint
FILES=`find web-app/js/ -name "*.js" | grep -v jqplot | grep -v jquery`
echo "# Linting: $FILES"
jslint --white --sloppy --white --browser --nomen --plusplus --forin \
--predef $ \
--predef jQuery \
--predef url_root \
--predef i18n \
--predef initializePopup \
-- $FILES
