#!/bin/sh
set -e

# check spidermonkey is installed
jslint || echo "Please install jslint"

# check that jslint is available in temp

# run jslint
if [ -z "$@" ]; then
	FILES=`find web-app/js/ -name "*.js" | grep -v jqplot | grep -v jquery`
else
	FILES="$@"
fi

echo "# Linting: $FILES"
jslint --white --sloppy --white --browser --nomen --plusplus --forin --undef \
--predef $ \
--predef jQuery \
--predef url_root \
--predef i18n \
--predef initializePopup \
-- $FILES
