#!/bin/bash
count=`git status --porcelain | wc -c`
if [ $count -ne 0 ]; then
	echo "git status is not clean, stage and commit changes first"
	exit 1
else
	git checkout master
	git pull	
	git checkout -b $1
	git push -u origin $1
	wget "http://192.168.0.200/exec_script.php?user=jenkins&cmd=clone_jenkins_job&args=frontlinesms2-core-master%20$1%20frontlinesms2-$1"
	git add exec_script.php\?user=jenkins\&cmd=clone_jenkins_job\&args=frontlinesms2-core-master\ $1\ frontlinesms2-$1
	git rm -f exec_script.php\?user=jenkins\&cmd=clone_jenkins_job\&args=frontlinesms2-core-master\ $1\ frontlinesms2-$1
fi
