#!/bin/bash
echo "Building new release"
echo "Checking for clean repository..."
if test -n "$(git status --porcelain)"
then
	echo "FAILURE: Your repository is not clean. This script can only build from a clean repo"
	exit 1
fi
# TODO: i18n

# TODO: roll version numbers to non-snapshot
echo "Rolling version numbers to non-snapshot"
do/remove_snapshot_from_install_resource_directories

# TODO: do builds
echo "Building installers.."
grails prod BuildInstallers

# TODO: test build in appropriate format for machine
#### This can reuse elements of build_uninstall_install_test

# TODO: commit
#### git commit -m "Build for 2.a.b"
#### git push

# TODO: tag commit
#### git tag frontlinesms2.a.b
#### git push

# TODO: prompt user for new snapshot version number
#### prompt for new snapshot number

# TODO: roll version to new snapshot
#### similar to do/remove_snapshot_from_install_resource_directories

# TODO: commit with new snapshot version
#### git commit -m "Rolled version numbers to 2.x.y snapshot after 2.a.b release"

# TODO: git push --tags

# TODO: upload builds
#### CORE-1440

