#!/bin/bash
set -e
echo "# Removing -SNAPSHOT to resource.path values for installer..."
sed -i ": repeat; s:\(-Dfrontlinesms\.resource\.path=~/.*\)-SNAPSHOT</string>:\1</string>:; t repeat" ../frontlinesms-core/install/build.install4j
sed -i -e ": repeat; s:\(resource\.path=.*\)-SNAPSHOT:\1:; t repeat" ../frontlinesms-core/install/fileset/filtered/launcher.properties

echo "# TODO update this to support other flavours than core"
do/install_property_to_release install4j.applicationId

