#!/bin/bash

echo "Clearing snapshot directories..."

while read dir; do
	if [ -n "$dir" ]; then
		echo "Removing snapshot directory: $dir"
		rm -rf ~/.ivy2/cache/$dir
		rm -rf ~/.grails/ivy-cache/$dir
	fi
done < 'snapshots.list'

echo "Calling 'grails $@'"
grails $@

